[package]
name = "rust-bittorrent"
version = "0.1.0"
authors = ["Kolbjørn Austreng <aschenhaug@gmail.com>"]
edition = "2021"

[dependencies]
hex = "0.4.3"
reqwest = { version = "0.12.4", features = ["blocking"] }
sha1 = "0.10.6"
